/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waterbillingsystem_1.pkg0.pkg0.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import waterbillingsystem_1.pkg0.pkg0.JOptionPaneCustom;
import waterbillingsystem_1.pkg0.pkg0.base.BillData;
import waterbillingsystem_1.pkg0.pkg0.controller.BillDataProcessor;
import waterbillingsystem_1.pkg0.pkg0.controller.FillGUIComponents;

/**
 *
 * @author UDISSSA1
 */
public class EnterBillData extends javax.swing.JFrame {

    /**
     * Creates new form EnterBillData
     */
    public EnterBillData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        CDFLabelMain = new javax.swing.JLabel();
        BDLblNIC = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtCustomerNIC = new javax.swing.JTextField();
        BDLblCID = new javax.swing.JLabel();
        txtCustomerCID = new javax.swing.JTextField();
        BDLblUnits = new javax.swing.JLabel();
        radioUnits = new javax.swing.JRadioButton();
        radioMeter = new javax.swing.JRadioButton();
        txtPaymentAmt = new javax.swing.JTextField();
        ckBoxSramadhana = new javax.swing.JCheckBox();
        ckBoxAbsentFee = new javax.swing.JCheckBox();
        BDLblUnits1 = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        btnBDClear = new javax.swing.JButton();
        btnBDEnter = new javax.swing.JButton();
        btnBDEnterAnother = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CDFLabelMain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CDFLabelMain.setText("Bill Data Form");

        BDLblNIC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDLblNIC.setText("Customer NIC");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select NIC" }));

        txtCustomerNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerNICKeyTyped(evt);
            }
        });

        BDLblCID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDLblCID.setText("Customer Id");

        txtCustomerCID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerCIDKeyTyped(evt);
            }
        });

        BDLblUnits.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDLblUnits.setText("Monthly Unit Usage");

        buttonGroup1.add(radioUnits);
        radioUnits.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioUnits.setText("Monthly unit usage");

        buttonGroup1.add(radioMeter);
        radioMeter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioMeter.setText("Current units in meter");

        txtPaymentAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaymentAmtKeyTyped(evt);
            }
        });

        ckBoxSramadhana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckBoxSramadhana.setText("  Sramadhana Fee");

        ckBoxAbsentFee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckBoxAbsentFee.setText("  Absent Charge");

        BDLblUnits1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDLblUnits1.setText("Billing Month");

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01-January", "02-February", "03-March", "04-April", "05-May", "06-June", "07-July", "08-August", "09-September", "10-Octomber", "11-November", "12-December" }));

        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));

        btnBDClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBDClear.setText(" Clear Bill Data");
        btnBDClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDClearActionPerformed(evt);
            }
        });

        btnBDEnter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBDEnter.setText("Enter Bill");
        btnBDEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDEnterActionPerformed(evt);
            }
        });

        btnBDEnterAnother.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBDEnterAnother.setText("Another Bill");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(CDFLabelMain))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBDClear)
                                .addGap(66, 66, 66)
                                .addComponent(btnBDEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBDEnterAnother, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BDLblUnits1)
                                .addGap(79, 79, 79)
                                .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BDLblNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDLblCID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDLblUnits))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radioUnits)
                        .addGap(27, 27, 27)
                        .addComponent(radioMeter)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPaymentAmt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomerCID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomerNIC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(58, 58, 58))))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckBoxAbsentFee)
                    .addComponent(ckBoxSramadhana))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(CDFLabelMain)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDLblNIC)
                    .addComponent(txtCustomerNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDLblCID)
                    .addComponent(txtCustomerCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPaymentAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDLblUnits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMeter)
                    .addComponent(radioUnits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckBoxSramadhana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckBoxAbsentFee)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BDLblUnits1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBDClear)
                    .addComponent(btnBDEnterAnother)
                    .addComponent(btnBDEnter))
                .addGap(46, 46, 46))
        );

        radioMeter.getAccessibleContext().setAccessibleParent(radioMeter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBDEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDEnterActionPerformed
        // TODO add your handling code here:
        boolean overall = false;
        BillData billData=new BillData();
        billData.setNic(txtCustomerNIC.getText());
        billData.setCid(txtCustomerCID.getText());
        if(radioUnits.isSelected())
            billData.setMonthlyUsageUnit(Integer.parseInt(txtPaymentAmt.getText()));
        if(radioMeter.isSelected())
            billData.setNewMeter(Integer.parseInt(txtPaymentAmt.getText()));
        if(ckBoxSramadhana.isSelected())
            billData.setSramadhana(true);
        else
            billData.setSramadhana(false);
        if(ckBoxAbsentFee.isSelected())
            billData.setAbsentCharge(true);
        else
            billData.setAbsentCharge(false);
        
        billData.setMonth(cmbMonth.getSelectedItem().toString().split("-")[0]+cmbYear.getSelectedItem().toString());
        
        BillDataProcessor BillDataProcessor=new BillDataProcessor();
        if(BillDataProcessor.putBillData(billData))
        {
            java.util.logging.Logger.getLogger(EnterBillData.class.getName()).log(java.util.logging.Level.SEVERE, null, billData.getMbid()+": Successfully data inserted");
            overall =true;
        }
        else
            overall =false;
        BillDataProcessor billDataProcessor=new BillDataProcessor();
        
        try {
            if(billDataProcessor.setMonthlyBillDetails(billData))
            {
               java.util.logging.Logger.getLogger(EnterBillData.class.getName()).log(java.util.logging.Level.SEVERE, null, billData.getMbid()+": with MonthlyBillDetails successfully data inserted"); 
               overall =true;
            }   
            else
                overall =false;
                } catch (Exception ex) {
            Logger.getLogger(EnterBillData.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPaneCustom.errorBox("Bill data inserted error: " +ex.getMessage(), "Bill Data Insertion");
        }
        if(overall)
            JOptionPaneCustom.infoBox("Bill data inserted successfully", "Bill Data Insertion");
    }//GEN-LAST:event_btnBDEnterActionPerformed

    private void btnBDClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDClearActionPerformed
        // TODO add your handling code here:
        txtCustomerNIC.setText("");
        txtCustomerCID.setText("");
        txtPaymentAmt.setText("");
        if(radioUnits.isSelected() || radioMeter.isSelected())
            buttonGroup1.clearSelection();
        ckBoxSramadhana.setSelected(false);
        ckBoxAbsentFee.setSelected(false);
        cmbMonth.setSelectedIndex(0);
        cmbYear.setSelectedIndex(0);
    }//GEN-LAST:event_btnBDClearActionPerformed

    private void txtCustomerNICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNICKeyTyped
        FillGUIComponents.setNumberOnlyTextBox(evt);
    }//GEN-LAST:event_txtCustomerNICKeyTyped

    private void txtCustomerCIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerCIDKeyTyped
        // TODO add your handling code here:
        FillGUIComponents.setNumberOnlyTextBox(evt);
    }//GEN-LAST:event_txtCustomerCIDKeyTyped

    private void txtPaymentAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentAmtKeyTyped
        // TODO add your handling code here:
        FillGUIComponents.setNumberOnlyTextBox(evt);
    }//GEN-LAST:event_txtPaymentAmtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterBillData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EnterBillData().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BDLblCID;
    private javax.swing.JLabel BDLblNIC;
    private javax.swing.JLabel BDLblUnits;
    private javax.swing.JLabel BDLblUnits1;
    private javax.swing.JLabel CDFLabelMain;
    private javax.swing.JButton btnBDClear;
    private javax.swing.JButton btnBDEnter;
    private javax.swing.JButton btnBDEnterAnother;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckBoxAbsentFee;
    private javax.swing.JCheckBox ckBoxSramadhana;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JRadioButton radioMeter;
    private javax.swing.JRadioButton radioUnits;
    private javax.swing.JTextField txtCustomerCID;
    private javax.swing.JTextField txtCustomerNIC;
    private javax.swing.JTextField txtPaymentAmt;
    // End of variables declaration//GEN-END:variables
}
