/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waterbillingsystem_1.pkg0.pkg0.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import waterbillingsystem_1.pkg0.pkg0.JOptionPaneCustom;
import waterbillingsystem_1.pkg0.pkg0.base.Customer;
import waterbillingsystem_1.pkg0.pkg0.controller.CustomerDataProcessor;
import waterbillingsystem_1.pkg0.pkg0.controller.FillGUIComponents;
import waterbillingsystem_1.pkg0.pkg0.logging.getLogger;

/**
 *
 * @author UDISSSA1
 */
public class EnterCustomer extends javax.swing.JFrame {

    /**
     * Creates new form EnterCustomer
     */
    boolean dataUpdate ;  
    boolean dataInserted;
    public EnterCustomer() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        dataUpdate = false;
        dataInserted =false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CDFLabelMain = new javax.swing.JLabel();
        CDFLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCustomername = new javax.swing.JTextArea();
        CDFLabel3 = new javax.swing.JLabel();
        txtCustomerNIC = new javax.swing.JTextField();
        CDFLabel4 = new javax.swing.JLabel();
        CDFLabel5 = new javax.swing.JLabel();
        txtCustomerAd1 = new javax.swing.JTextField();
        CDFLabel6 = new javax.swing.JLabel();
        CDFLabel7 = new javax.swing.JLabel();
        txtCustomerAd2 = new javax.swing.JTextField();
        txtCustomerAd3 = new javax.swing.JTextField();
        CDFLabel8 = new javax.swing.JLabel();
        txtCustomerNo = new javax.swing.JTextField();
        cmbGroupId = new javax.swing.JComboBox<>();
        btnCDFClear = new javax.swing.JButton();
        btnCDFEnter = new javax.swing.JButton();
        btnCDFEnterAnother = new javax.swing.JButton();
        lblCDFMeterNo = new javax.swing.JLabel();
        txtCustomerMno = new javax.swing.JTextField();
        txtCustomerTOA = new javax.swing.JTextField();
        CDFLabelCM = new javax.swing.JLabel();
        txtCustomerCurrentMeter = new javax.swing.JTextField();
        lblCDFTOA = new javax.swing.JLabel();
        CDFLabelCFN = new javax.swing.JLabel();
        txtCustomerFN = new javax.swing.JTextField();
        btnCDHome = new javax.swing.JButton();
        btnCDUpdate = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        CDFLabelMain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CDFLabelMain.setText("Customer Details Form");

        CDFLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CDFLabel2.setText("Customer Full Name");

        txtCustomername.setColumns(20);
        txtCustomername.setRows(5);
        jScrollPane1.setViewportView(txtCustomername);

        CDFLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CDFLabel3.setText("Customer NIC");

        txtCustomerNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerNICKeyTyped(evt);
            }
        });

        CDFLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CDFLabel4.setText("Customer Group");

        CDFLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CDFLabel5.setText("Customer Address line 1");

        CDFLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CDFLabel6.setText("Customer Address line 2");

        CDFLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CDFLabel7.setText("Customer Address line 3");

        CDFLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CDFLabel8.setText("Customer No");

        txtCustomerNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerNoKeyTyped(evt);
            }
        });

        cmbGroupId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "group-1", "group-2", "group-3", "group-4" }));

        btnCDFClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCDFClear.setText(" Clear Data");
        btnCDFClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDFClearActionPerformed(evt);
            }
        });

        btnCDFEnter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCDFEnter.setText("Enter Customer");
        btnCDFEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDFEnterActionPerformed(evt);
            }
        });

        btnCDFEnterAnother.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCDFEnterAnother.setText("Another Customer");
        btnCDFEnterAnother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDFEnterAnotherActionPerformed(evt);
            }
        });

        lblCDFMeterNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCDFMeterNo.setText("Meter No");

        txtCustomerMno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerMnoKeyTyped(evt);
            }
        });

        txtCustomerTOA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerTOAKeyTyped(evt);
            }
        });

        CDFLabelCM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CDFLabelCM.setText("Current Meter");

        txtCustomerCurrentMeter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerCurrentMeterKeyTyped(evt);
            }
        });

        lblCDFTOA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCDFTOA.setText("Total Outstanding Amount");

        CDFLabelCFN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CDFLabelCFN.setText("Customer First Name");

        btnCDHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_button.png"))); // NOI18N
        btnCDHome.setBorder(null);
        btnCDHome.setBorderPainted(false);
        btnCDHome.setContentAreaFilled(false);
        btnCDHome.setFocusPainted(false);
        btnCDHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDHomeActionPerformed(evt);
            }
        });

        btnCDUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnCDUpdate.setBorder(null);
        btnCDUpdate.setBorderPainted(false);
        btnCDUpdate.setContentAreaFilled(false);
        btnCDUpdate.setFocusPainted(false);
        btnCDUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCDUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CDFLabelMain)
                        .addGap(100, 100, 100)
                        .addComponent(btnCDHome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CDFLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustomerNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(CDFLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCDFMeterNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustomerMno, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CDFLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustomerAd3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CDFLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustomerAd2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(CDFLabel4)
                                .addGap(108, 108, 108)
                                .addComponent(cmbGroupId, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(CDFLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustomerAd1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CDFLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCDFTOA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(txtCustomerTOA, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CDFLabelCM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustomerCurrentMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnCDFClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCDFEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnCDFEnterAnother)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CDFLabelCFN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustomerFN, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCDHome)
                    .addComponent(CDFLabelMain)
                    .addComponent(btnCDUpdate))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CDFLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CDFLabelCFN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CDFLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(CDFLabel4)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmbGroupId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCustomerAd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CDFLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDFLabel6)
                    .addComponent(txtCustomerAd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDFLabel7)
                    .addComponent(txtCustomerAd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDFLabel8)
                    .addComponent(txtCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCDFMeterNo)
                    .addComponent(txtCustomerMno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDFLabelCM)
                    .addComponent(txtCustomerCurrentMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCDFTOA)
                    .addComponent(txtCustomerTOA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCDFEnter)
                    .addComponent(btnCDFEnterAnother)
                    .addComponent(btnCDFClear))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCDFEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDFEnterActionPerformed
        Customer customer=new Customer();
        
        customer.setCFirstName(txtCustomerFN.getText());
        customer.setCid(txtCustomerNo.getText());
        customer.setNic(txtCustomerNIC.getText() );
        customer.setGid(cmbGroupId.getSelectedItem().toString().split("-")[1]);
        customer.setAddress_1(txtCustomerAd1.getText());
        customer.setAddress_2(txtCustomerAd2.getText());
        customer.setAddress_3(txtCustomerAd3.getText());
        customer.setCname(txtCustomername.getText());
        customer.setMeterNo(txtCustomerMno.getText());
        customer.setCurrentMeter(Integer.parseInt(txtCustomerCurrentMeter.getText()));
        customer.setTotalOutstandingAmount(Double.parseDouble(txtCustomerTOA.getText()));        
        if(dataUpdate && !dataInserted)
        {
            UpdateCustomerData(customer);
        }
        else if(!dataInserted)
        {
            InsertCustomerData(customer);
        }

    }//GEN-LAST:event_btnCDFEnterActionPerformed

    private void InsertCustomerData(Customer customer){

        if(CustomerDataProcessor.putCustomer(customer))
        {
            JOptionPaneCustom.infoBox("Customer data inserted successfully", "Bill Data Insertion");
            getLogger.getLog().debug("Customer data inserted :"+customer.getNic());
            dataInserted = true;
            ClearComponents();            
        }
        else 
            JOptionPaneCustom.errorBox("Customer data insertion failed", "Customer Data Insertion");    
    }
    private void UpdateCustomerData(Customer customer){
        
        if(CustomerDataProcessor.updateCustomer(customer))
        {
            JOptionPaneCustom.infoBox("Customer data updated successfully", "Bill Data Insertion");
            getLogger.getLog().debug("Customer data inserted :"+customer.getNic());
            dataInserted = true;
            ClearComponents();  
            dataUpdate=false;
            btnCDFEnter.setText("Enter Customer");
            txtCustomerNo.enable();
        }
        else 
            JOptionPaneCustom.errorBox("Customer data insertion failed", "Customer Data Insertion");          
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            FillGUIComponents fillGUIComponents=new FillGUIComponents();
            // TODO add your handling code here:
            fillGUIComponents.FillcmbGroupId(cmbGroupId);
        } catch (SQLException ex) {
            Logger.getLogger(EnterCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(EnterCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnCDFClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDFClearActionPerformed

        ClearComponents();
    }//GEN-LAST:event_btnCDFClearActionPerformed

    private void ClearComponents(){
        txtCustomername.setText("");
        txtCustomerNIC.setText("");
        cmbGroupId.setSelectedIndex(0);
        txtCustomerAd1.setText("");
        txtCustomerAd2.setText("");
        txtCustomerAd3.setText("");
        txtCustomerNo.setText("");
        txtCustomerMno.setText("");
        txtCustomerCurrentMeter.setText("");
        txtCustomerTOA.setText("");  
        txtCustomerFN.setText("");
        
    }
    
    private void txtCustomerNICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNICKeyTyped

        FillGUIComponents.setNumberOnlyTextBoxNIC(evt);
    }//GEN-LAST:event_txtCustomerNICKeyTyped

    private void txtCustomerNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNoKeyTyped

        FillGUIComponents.setNumberOnlyTextBox(evt);
    }//GEN-LAST:event_txtCustomerNoKeyTyped

    private void txtCustomerMnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerMnoKeyTyped

        FillGUIComponents.setNumberOnlyTextBox(evt);
    }//GEN-LAST:event_txtCustomerMnoKeyTyped

    private void txtCustomerTOAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerTOAKeyTyped
        // TODO add your handling code here:
        FillGUIComponents.setNumberOnlyTextBox(evt);
    }//GEN-LAST:event_txtCustomerTOAKeyTyped

    private void txtCustomerCurrentMeterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerCurrentMeterKeyTyped
        // TODO add your handling code here:
        FillGUIComponents.setNumberOnlyTextBox(evt);
    }//GEN-LAST:event_txtCustomerCurrentMeterKeyTyped

    private void btnCDHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDHomeActionPerformed
        // TODO add your handling code here:
        MainPage mainPage=new MainPage();
        mainPage.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCDHomeActionPerformed

    private void btnCDUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDUpdateActionPerformed
        // TODO add your handling code here:
        if (!dataUpdate)
            dataUpdate = true;
        
        CustomerDataProcessor customerDataProcessor=new CustomerDataProcessor();
        try {
            Customer customer = customerDataProcessor.getCustomer(txtCustomerNIC.getText());
            
            //txtCustomerNIC.disable();
            txtCustomerNo.setText(customer.getCid());
            txtCustomerFN.setText(customer.getCFirstName());
            txtCustomername.setText(customer.getCname());
            cmbGroupId.setSelectedItem(customer.getGid());
            txtCustomername.setText(customer.getCname());
            
            FillGUIComponents fillGUIComponents =new FillGUIComponents();
            fillGUIComponents.updateCmb(cmbGroupId, customer.getGid());
            
            txtCustomerAd1.setText(customer.getAddress_1());
            txtCustomerAd2.setText(customer.getAddress_2());
            txtCustomerAd3.setText(customer.getAddress_3());
            
            txtCustomerNo.disable();
            txtCustomerMno.setText(customer.getMeterNo());
            txtCustomerCurrentMeter.setText(String.valueOf(customer.getCurrentMeter()) );
            txtCustomerTOA.setText(String.valueOf(customer.getTotalOutstandingAmount()));
            
            btnCDFEnter.setText("Update Customer");
            dataInserted=false;
            dataUpdate = true;
            
        } catch (Exception ex) {
            JOptionPaneCustom.errorBox("NIC not found", "Customer Data Updating");
            Logger.getLogger(EnterCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCDUpdateActionPerformed

    private void btnCDFEnterAnotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDFEnterAnotherActionPerformed
        // TODO add your handling code here:
        if(dataInserted)
        {
            ClearComponents();
            dataInserted = false;
        }
        else
            JOptionPaneCustom.errorBox("Current insertion not completed", "Customer Data Insertion");        
    }//GEN-LAST:event_btnCDFEnterAnotherActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.InstantiationException
     */
    public static void main(String args[]) throws InstantiationException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EnterCustomer().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CDFLabel2;
    private javax.swing.JLabel CDFLabel3;
    private javax.swing.JLabel CDFLabel4;
    private javax.swing.JLabel CDFLabel5;
    private javax.swing.JLabel CDFLabel6;
    private javax.swing.JLabel CDFLabel7;
    private javax.swing.JLabel CDFLabel8;
    private javax.swing.JLabel CDFLabelCFN;
    private javax.swing.JLabel CDFLabelCM;
    private javax.swing.JLabel CDFLabelMain;
    private javax.swing.JButton btnCDFClear;
    private javax.swing.JButton btnCDFEnter;
    private javax.swing.JButton btnCDFEnterAnother;
    private javax.swing.JButton btnCDHome;
    private javax.swing.JButton btnCDUpdate;
    private javax.swing.JComboBox<String> cmbGroupId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCDFMeterNo;
    private javax.swing.JLabel lblCDFTOA;
    private javax.swing.JTextField txtCustomerAd1;
    private javax.swing.JTextField txtCustomerAd2;
    private javax.swing.JTextField txtCustomerAd3;
    private javax.swing.JTextField txtCustomerCurrentMeter;
    private javax.swing.JTextField txtCustomerFN;
    private javax.swing.JTextField txtCustomerMno;
    private javax.swing.JTextField txtCustomerNIC;
    private javax.swing.JTextField txtCustomerNo;
    private javax.swing.JTextField txtCustomerTOA;
    private javax.swing.JTextArea txtCustomername;
    // End of variables declaration//GEN-END:variables
}