/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waterbillingsystem_1.pkg0.pkg0.view;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import waterbillingsystem_1.pkg0.pkg0.JOptionPaneCustom;
import waterbillingsystem_1.pkg0.pkg0.VariableStorage;
import waterbillingsystem_1.pkg0.pkg0.base.Customer;
import waterbillingsystem_1.pkg0.pkg0.controller.CustomerDataProcessor;
import waterbillingsystem_1.pkg0.pkg0.controller.FillGUIComponents;

/**
 *
 * @author UDISSSA1
 */
public class FindCustomer extends javax.swing.JFrame {

    /**
     * Creates new form FindCustomer
     * @throws java.io.IOException
     */
    public FindCustomer() throws IOException {
        File imageFile = new File(VariableStorage.getBackupGroundImage());
        BufferedImage myImage = ImageIO.read(imageFile);
        this.setContentPane(new ImagePanel(myImage));
        
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);        
        ImageIcon img = new ImageIcon(VariableStorage.getImageIcon());
        this.setIconImage(img.getImage());  
        resetLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMainCustomer = new javax.swing.JButton();
        FClblCID = new javax.swing.JLabel();
        FClblNIC = new javax.swing.JLabel();
        FClblIName = new javax.swing.JLabel();
        FClblFName = new javax.swing.JLabel();
        FClblCG = new javax.swing.JLabel();
        FClblCAL1 = new javax.swing.JLabel();
        FClblCAL2 = new javax.swing.JLabel();
        FClblCAL3 = new javax.swing.JLabel();
        FClblMNo = new javax.swing.JLabel();
        FClblCM = new javax.swing.JLabel();
        FClblTOA = new javax.swing.JLabel();
        FClblIF = new javax.swing.JLabel();
        FClblIRPayment = new javax.swing.JLabel();
        FClblCMAns = new javax.swing.JLabel();
        FClblTOAAns = new javax.swing.JLabel();
        FClblIFAns = new javax.swing.JLabel();
        FClblNICAns = new javax.swing.JLabel();
        FClblIRPaymentAns = new javax.swing.JLabel();
        FClblINameAns = new javax.swing.JLabel();
        FClblFNameAns = new javax.swing.JLabel();
        FClblCGAns = new javax.swing.JLabel();
        FClblCAL1Ans = new javax.swing.JLabel();
        FClblCAL2Ans = new javax.swing.JLabel();
        FClblCAL3Ans = new javax.swing.JLabel();
        FClblMNoAns = new javax.swing.JLabel();
        txtCustomerNo = new javax.swing.JTextField();
        btnCDUpdate = new javax.swing.JButton();
        btnCDHome = new javax.swing.JButton();
        FCLabelMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(623, 555));
        setResizable(false);

        btnMainCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer.png"))); // NOI18N
        btnMainCustomer.setBorder(null);
        btnMainCustomer.setBorderPainted(false);
        btnMainCustomer.setContentAreaFilled(false);
        btnMainCustomer.setFocusPainted(false);
        btnMainCustomer.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        btnMainCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainCustomerActionPerformed(evt);
            }
        });

        FClblCID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCID.setText("Customer No");

        FClblNIC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblNIC.setText("Customer NIC");

        FClblIName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblIName.setText("Customer Identifying Name");

        FClblFName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblFName.setText("Customer Full Name");

        FClblCG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCG.setText("Customer Group");

        FClblCAL1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCAL1.setText("Customer Address line 1");

        FClblCAL2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCAL2.setText("Customer Address line 2");

        FClblCAL3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCAL3.setText("Customer Address line 3");

        FClblMNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblMNo.setText("Meter No");

        FClblCM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCM.setText("Current Meter");

        FClblTOA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblTOA.setText("Total Outstanding Amount");

        FClblIF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblIF.setText("Initial Fee");

        FClblIRPayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblIRPayment.setText("Initial Recived Payment");

        FClblCMAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCMAns.setText("...");

        FClblTOAAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblTOAAns.setText("...");

        FClblIFAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblIFAns.setText("...");

        FClblNICAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblNICAns.setText("...");

        FClblIRPaymentAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblIRPaymentAns.setText("...");

        FClblINameAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblINameAns.setText("...");

        FClblFNameAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblFNameAns.setText("...");

        FClblCGAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCGAns.setText("...");

        FClblCAL1Ans.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCAL1Ans.setText("...");

        FClblCAL2Ans.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCAL2Ans.setText("...");

        FClblCAL3Ans.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblCAL3Ans.setText("...");

        FClblMNoAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FClblMNoAns.setText("...");

        txtCustomerNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerNoKeyTyped(evt);
            }
        });

        btnCDUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnCDUpdate.setBorder(null);
        btnCDUpdate.setBorderPainted(false);
        btnCDUpdate.setContentAreaFilled(false);
        btnCDUpdate.setFocusPainted(false);
        btnCDUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDUpdateActionPerformed(evt);
            }
        });

        btnCDHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_button.png"))); // NOI18N
        btnCDHome.setBorder(null);
        btnCDHome.setBorderPainted(false);
        btnCDHome.setContentAreaFilled(false);
        btnCDHome.setFocusPainted(false);
        btnCDHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDHomeActionPerformed(evt);
            }
        });

        FCLabelMain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FCLabelMain.setText("Find Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FClblIName)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(FClblTOA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FClblCM, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(98, 98, 98))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FClblIF)
                                    .addGap(141, 141, 141))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FClblCAL3)
                                    .addGap(51, 51, 51))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FClblCAL2)
                                    .addGap(51, 51, 51))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FClblIRPayment)
                                    .addGap(56, 56, 56))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FClblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(FClblCAL1)
                                    .addGap(51, 51, 51)))
                            .addComponent(FClblCG)
                            .addComponent(FClblMNo)
                            .addComponent(FClblNIC)
                            .addComponent(FClblCID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FClblCAL1Ans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblNICAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblINameAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblFNameAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblCGAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblCAL2Ans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblCAL3Ans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblMNoAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblTOAAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblCMAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblIFAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FClblIRPaymentAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(txtCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(FCLabelMain)
                                .addGap(76, 76, 76)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMainCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCDUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnCDHome)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCDHome)
                    .addComponent(btnMainCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FCLabelMain))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FClblCID)
                        .addComponent(txtCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCDUpdate))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FClblNIC)
                        .addGap(18, 18, 18)
                        .addComponent(FClblIName)
                        .addGap(18, 18, 18)
                        .addComponent(FClblFName)
                        .addGap(18, 18, 18)
                        .addComponent(FClblCG)
                        .addGap(15, 15, 15)
                        .addComponent(FClblCAL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FClblCAL2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FClblCAL3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FClblMNo)
                        .addGap(18, 18, 18)
                        .addComponent(FClblCM)
                        .addGap(18, 18, 18)
                        .addComponent(FClblTOA)
                        .addGap(18, 18, 18)
                        .addComponent(FClblIF)
                        .addGap(18, 18, 18)
                        .addComponent(FClblIRPayment))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FClblNICAns)
                        .addGap(18, 18, 18)
                        .addComponent(FClblINameAns)
                        .addGap(18, 18, 18)
                        .addComponent(FClblFNameAns)
                        .addGap(18, 18, 18)
                        .addComponent(FClblCGAns)
                        .addGap(15, 15, 15)
                        .addComponent(FClblCAL1Ans)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FClblCAL2Ans)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FClblCAL3Ans)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FClblMNoAns)
                        .addGap(18, 18, 18)
                        .addComponent(FClblCMAns)
                        .addGap(18, 18, 18)
                        .addComponent(FClblTOAAns)
                        .addGap(18, 18, 18)
                        .addComponent(FClblIFAns)
                        .addGap(18, 18, 18)
                        .addComponent(FClblIRPaymentAns)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainCustomerActionPerformed
        openCustomerWindow();
    }//GEN-LAST:event_btnMainCustomerActionPerformed

    private void txtCustomerNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNoKeyTyped

        FillGUIComponents.setNumberOnlyTextBox(evt);
    }//GEN-LAST:event_txtCustomerNoKeyTyped

    private void btnCDUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDUpdateActionPerformed

        resetLabels();
        CustomerDataProcessor customerDataProcessor=new CustomerDataProcessor();
        try {
            Customer customer = customerDataProcessor.getCustomer(txtCustomerNo.getText());
            if(customer.getCid() != null)
            {
                FClblNICAns.setText(nullValidator(customer.getNic()));
                FClblINameAns.setText(nullValidator(customer.getCFirstName()));
                FClblFNameAns.setText(nullValidator(customer.getCname()));
                FClblCGAns.setText(nullValidator(customer.getGid()));
                FClblCAL1Ans.setText(nullValidator(customer.getAddress_1()));
                FClblCAL2Ans.setText(nullValidator(customer.getAddress_2()));
                FClblCAL3Ans.setText(nullValidator(customer.getAddress_3()));
                FClblMNoAns.setText(nullValidator(customer.getMeterNo()));
                FClblCMAns.setText(nullValidator(String.valueOf(customer.getCurrentMeter())));
                FClblTOAAns.setText(nullValidator(String.valueOf(customer.getTotalOutstandingAmount())));
                FClblIFAns.setText(nullValidator(String.valueOf(customer.getInitialFeeTotal())));
                FClblIRPaymentAns.setText(nullValidator(String.valueOf(customer.getInitialReceived())));
            }
            
        } catch (Exception ex) {
            JOptionPaneCustom.errorBox("Error in getting data for given Id", "Find Customer Data");   
            Logger.getLogger(FindCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCDUpdateActionPerformed

    private String nullValidator(String value){
    
        if("".equals(value))
            return VariableStorage.getEmptyString();
        else
            return value;
        
    }
    private void btnCDHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDHomeActionPerformed
        MainPage mainPage = null;
        try {
            mainPage = new MainPage();
        } catch (IOException ex) {
            Logger.getLogger(EnterCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainPage.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCDHomeActionPerformed

    private void openCustomerWindow(){
        EnterCustomer enterCustomer = null;
        try {
            enterCustomer = new EnterCustomer();
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterCustomer.setVisible(true); 
        this.setVisible(false);
        this.dispose();      
        
    }
    
    private void resetLabels(){
        
        FClblNICAns.setText(VariableStorage.getEmptyString());
        FClblINameAns.setText(VariableStorage.getEmptyString());
        FClblFNameAns.setText(VariableStorage.getEmptyString());
        FClblCGAns.setText(VariableStorage.getEmptyString());
        FClblCAL1Ans.setText(VariableStorage.getEmptyString());
        FClblCAL2Ans.setText(VariableStorage.getEmptyString());
        FClblCAL3Ans.setText(VariableStorage.getEmptyString());
        FClblMNoAns.setText(VariableStorage.getEmptyString());
        FClblCMAns.setText(VariableStorage.getEmptyString());
        FClblTOAAns.setText(VariableStorage.getEmptyString());
        FClblIFAns.setText(VariableStorage.getEmptyString());
        FClblIRPaymentAns.setText(VariableStorage.getEmptyString());        

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new FindCustomer().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(FindCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FCLabelMain;
    private javax.swing.JLabel FClblCAL1;
    private javax.swing.JLabel FClblCAL1Ans;
    private javax.swing.JLabel FClblCAL2;
    private javax.swing.JLabel FClblCAL2Ans;
    private javax.swing.JLabel FClblCAL3;
    private javax.swing.JLabel FClblCAL3Ans;
    private javax.swing.JLabel FClblCG;
    private javax.swing.JLabel FClblCGAns;
    private javax.swing.JLabel FClblCID;
    private javax.swing.JLabel FClblCM;
    private javax.swing.JLabel FClblCMAns;
    private javax.swing.JLabel FClblFName;
    private javax.swing.JLabel FClblFNameAns;
    private javax.swing.JLabel FClblIF;
    private javax.swing.JLabel FClblIFAns;
    private javax.swing.JLabel FClblIName;
    private javax.swing.JLabel FClblINameAns;
    private javax.swing.JLabel FClblIRPayment;
    private javax.swing.JLabel FClblIRPaymentAns;
    private javax.swing.JLabel FClblMNo;
    private javax.swing.JLabel FClblMNoAns;
    private javax.swing.JLabel FClblNIC;
    private javax.swing.JLabel FClblNICAns;
    private javax.swing.JLabel FClblTOA;
    private javax.swing.JLabel FClblTOAAns;
    private javax.swing.JButton btnCDHome;
    private javax.swing.JButton btnCDUpdate;
    private javax.swing.JButton btnMainCustomer;
    private javax.swing.JTextField txtCustomerNo;
    // End of variables declaration//GEN-END:variables
}
