/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waterbillingsystem_1.pkg0.pkg0.view;

import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.io.File;
import java.io.IOException;
/**
 *
 * @author UDISSSA1
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Main
     * @throws java.io.IOException
     */
    
    public MainPage() throws IOException {  
        
        File imageFile = new File("images\\wallpaper.png");
        BufferedImage myImage = ImageIO.read(imageFile);
        this.setContentPane(new ImagePanel(myImage));
        
        initComponents();
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
        ImageIcon imageIcon = new ImageIcon("images\\WaterDrop.png");
        this.setIconImage(imageIcon.getImage());          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMainTrx = new javax.swing.JPanel();
        btnMainPayment = new javax.swing.JButton();
        lblMainPayments = new javax.swing.JLabel();
        btnMainBD = new javax.swing.JButton();
        lblMainBill = new javax.swing.JLabel();
        btnMainUP = new javax.swing.JButton();
        lblMainUP = new javax.swing.JLabel();
        LblMain1 = new javax.swing.JLabel();
        PanelMainRpt = new javax.swing.JPanel();
        btnMainInvoice = new javax.swing.JButton();
        lblMainCustomer2 = new javax.swing.JLabel();
        LblMain2 = new javax.swing.JLabel();
        PanelMainUserM = new javax.swing.JPanel();
        btnMainCustomer = new javax.swing.JButton();
        btnGroupD = new javax.swing.JButton();
        lblMainCustomer = new javax.swing.JLabel();
        lblMainGD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pananwala Water Billing System");
        setName("frmMain"); // NOI18N
        setResizable(false);

        PanelMainTrx.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transactions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PanelMainTrx.setForeground(new java.awt.Color(255, 255, 255));
        PanelMainTrx.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelMainTrx.setOpaque(false);

        btnMainPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payments.png"))); // NOI18N
        btnMainPayment.setBorder(null);
        btnMainPayment.setBorderPainted(false);
        btnMainPayment.setContentAreaFilled(false);
        btnMainPayment.setFocusPainted(false);
        btnMainPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainPaymentActionPerformed(evt);
            }
        });

        lblMainPayments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMainPayments.setText("Payments");

        btnMainBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill.png"))); // NOI18N
        btnMainBD.setBorder(null);
        btnMainBD.setBorderPainted(false);
        btnMainBD.setContentAreaFilled(false);
        btnMainBD.setFocusPainted(false);
        btnMainBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainBDActionPerformed(evt);
            }
        });

        lblMainBill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMainBill.setText("Bill Data");

        btnMainUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uintp.png"))); // NOI18N
        btnMainUP.setBorder(null);
        btnMainUP.setBorderPainted(false);
        btnMainUP.setContentAreaFilled(false);
        btnMainUP.setFocusPainted(false);
        btnMainUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainUPActionPerformed(evt);
            }
        });

        lblMainUP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMainUP.setText("Unit Price");

        javax.swing.GroupLayout PanelMainTrxLayout = new javax.swing.GroupLayout(PanelMainTrx);
        PanelMainTrx.setLayout(PanelMainTrxLayout);
        PanelMainTrxLayout.setHorizontalGroup(
            PanelMainTrxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainTrxLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnMainPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMainPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnMainBD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMainBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnMainUP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMainUP, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        PanelMainTrxLayout.setVerticalGroup(
            PanelMainTrxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainTrxLayout.createSequentialGroup()
                .addGroup(PanelMainTrxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMainPayment)
                    .addComponent(btnMainBD)
                    .addGroup(PanelMainTrxLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(PanelMainTrxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMainPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelMainTrxLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblMainUP, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnMainUP)
                            .addComponent(lblMainBill, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LblMain1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        LblMain1.setText("Pananwala Water Billing");

        PanelMainRpt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PanelMainRpt.setForeground(new java.awt.Color(255, 255, 255));
        PanelMainRpt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelMainRpt.setOpaque(false);

        btnMainInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoices.png"))); // NOI18N
        btnMainInvoice.setBorder(null);
        btnMainInvoice.setBorderPainted(false);
        btnMainInvoice.setContentAreaFilled(false);
        btnMainInvoice.setFocusPainted(false);
        btnMainInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainInvoiceActionPerformed(evt);
            }
        });

        lblMainCustomer2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMainCustomer2.setText("Generate Invoice");

        javax.swing.GroupLayout PanelMainRptLayout = new javax.swing.GroupLayout(PanelMainRpt);
        PanelMainRpt.setLayout(PanelMainRptLayout);
        PanelMainRptLayout.setHorizontalGroup(
            PanelMainRptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainRptLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(btnMainInvoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMainCustomer2)
                .addGap(28, 28, 28))
        );
        PanelMainRptLayout.setVerticalGroup(
            PanelMainRptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainRptLayout.createSequentialGroup()
                .addGroup(PanelMainRptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMainRptLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblMainCustomer2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMainRptLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnMainInvoice)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        LblMain2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        LblMain2.setText("System");

        PanelMainUserM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PanelMainUserM.setForeground(new java.awt.Color(255, 255, 255));
        PanelMainUserM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelMainUserM.setOpaque(false);

        btnMainCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer.png"))); // NOI18N
        btnMainCustomer.setBorder(null);
        btnMainCustomer.setBorderPainted(false);
        btnMainCustomer.setContentAreaFilled(false);
        btnMainCustomer.setFocusPainted(false);
        btnMainCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainCustomerActionPerformed(evt);
            }
        });

        btnGroupD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        btnGroupD.setBorder(null);
        btnGroupD.setBorderPainted(false);
        btnGroupD.setContentAreaFilled(false);
        btnGroupD.setFocusPainted(false);
        btnGroupD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupDActionPerformed(evt);
            }
        });

        lblMainCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMainCustomer.setText("Customer Data");

        lblMainGD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMainGD.setText("Group Data");

        javax.swing.GroupLayout PanelMainUserMLayout = new javax.swing.GroupLayout(PanelMainUserM);
        PanelMainUserM.setLayout(PanelMainUserMLayout);
        PanelMainUserMLayout.setHorizontalGroup(
            PanelMainUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainUserMLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(PanelMainUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGroupD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMainCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMainUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMainCustomer)
                    .addComponent(lblMainGD))
                .addGap(33, 33, 33))
        );
        PanelMainUserMLayout.setVerticalGroup(
            PanelMainUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainUserMLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PanelMainUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMainCustomer)
                    .addGroup(PanelMainUserMLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblMainCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelMainUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMainUserMLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGroupD))
                    .addGroup(PanelMainUserMLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblMainGD, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PanelMainUserM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblMain1)
                            .addComponent(LblMain2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(PanelMainRpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelMainTrx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelMainUserM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(PanelMainRpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(LblMain1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblMain2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(PanelMainTrx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainCustomerActionPerformed
        EnterCustomer enterCustomer = null;
        try {
            enterCustomer = new EnterCustomer();
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterCustomer.setVisible(true); 
        this.setVisible(false);
        this.dispose();  
    }//GEN-LAST:event_btnMainCustomerActionPerformed

    private void btnGroupDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupDActionPerformed
        // TODO add your handling code here:
        EnterGroup enterGroup = null;
        try {
            enterGroup = new EnterGroup();
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterGroup.setVisible(true); 
        this.setVisible(false);
        this.dispose();          
    }//GEN-LAST:event_btnGroupDActionPerformed

    private void btnMainInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainInvoiceActionPerformed
        // TODO add your handling code here:
        GenerateInvoice generateInvoice = null;
        try {
            generateInvoice = new GenerateInvoice();
        } catch (Exception ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        generateInvoice.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnMainInvoiceActionPerformed

    private void btnMainPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainPaymentActionPerformed
        // TODO add your handling code here:
        EnterPayment enterPayment = null;
        try {
            enterPayment = new EnterPayment();
        } catch (Exception ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterPayment.setVisible(true); 
        this.setVisible(false);
        this.dispose();            
    }//GEN-LAST:event_btnMainPaymentActionPerformed

    private void btnMainBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainBDActionPerformed
        // TODO add your handling code here:
        EnterBillData enterBillData = null;
        try {
            enterBillData = new EnterBillData();
        } catch (Exception ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterBillData.setVisible(true); 
        this.setVisible(false);
        this.dispose();         
    }//GEN-LAST:event_btnMainBDActionPerformed

    private void btnMainUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainUPActionPerformed
        // TODO add your handling code here:
        EnterUnitPrice enterUnitPrice = null;
        try {
            enterUnitPrice = new EnterUnitPrice();
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterUnitPrice.setVisible(true); 
        this.setVisible(false);
        this.dispose();             
    }//GEN-LAST:event_btnMainUPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MainPage().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblMain1;
    private javax.swing.JLabel LblMain2;
    private javax.swing.JPanel PanelMainRpt;
    private javax.swing.JPanel PanelMainTrx;
    private javax.swing.JPanel PanelMainUserM;
    private javax.swing.JButton btnGroupD;
    private javax.swing.JButton btnMainBD;
    private javax.swing.JButton btnMainCustomer;
    private javax.swing.JButton btnMainInvoice;
    private javax.swing.JButton btnMainPayment;
    private javax.swing.JButton btnMainUP;
    private javax.swing.JLabel lblMainBill;
    private javax.swing.JLabel lblMainCustomer;
    private javax.swing.JLabel lblMainCustomer2;
    private javax.swing.JLabel lblMainGD;
    private javax.swing.JLabel lblMainPayments;
    private javax.swing.JLabel lblMainUP;
    // End of variables declaration//GEN-END:variables
}
