/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waterbillingsystem_1.pkg0.pkg0.view;

import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.io.File;
import java.io.IOException;
/**
 *
 * @author UDISSSA1
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Main
     * @throws java.io.IOException
     */
    
    public MainPage() throws IOException {  
        
        File imageFile = new File("images\\wallpaper.png");
        BufferedImage myImage = ImageIO.read(imageFile);
        this.setContentPane(new ImagePanel(myImage));
        
        initComponents();
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
        ImageIcon imageIcon = new ImageIcon("images\\WaterDrop.png");
        this.setIconImage(imageIcon.getImage());          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMainTrx = new javax.swing.JPanel();
        btnPaymentD = new javax.swing.JButton();
        btnBillD = new javax.swing.JButton();
        btnUnitprice = new javax.swing.JButton();
        LblMain1 = new javax.swing.JLabel();
        PanelMainRpt = new javax.swing.JPanel();
        btnInvoice = new javax.swing.JButton();
        LblMain2 = new javax.swing.JLabel();
        PanelMainUserM = new javax.swing.JPanel();
        btnGroupD = new javax.swing.JButton();
        btnCustomerD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pananwala Water Billing System");
        setName("frmMain"); // NOI18N
        setResizable(false);

        PanelMainTrx.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transactions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PanelMainTrx.setForeground(new java.awt.Color(255, 255, 255));
        PanelMainTrx.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelMainTrx.setOpaque(false);

        btnPaymentD.setText("Payments Data");
        btnPaymentD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentDActionPerformed(evt);
            }
        });

        btnBillD.setText("Bill Data");
        btnBillD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillDActionPerformed(evt);
            }
        });

        btnUnitprice.setText("Unit Data");
        btnUnitprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnitpriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMainTrxLayout = new javax.swing.GroupLayout(PanelMainTrx);
        PanelMainTrx.setLayout(PanelMainTrxLayout);
        PanelMainTrxLayout.setHorizontalGroup(
            PanelMainTrxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainTrxLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnPaymentD, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnBillD, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnUnitprice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        PanelMainTrxLayout.setVerticalGroup(
            PanelMainTrxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainTrxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMainTrxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaymentD)
                    .addComponent(btnBillD)
                    .addComponent(btnUnitprice))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        LblMain1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        LblMain1.setText("Pananwala Water Billing");

        PanelMainRpt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PanelMainRpt.setForeground(new java.awt.Color(255, 255, 255));
        PanelMainRpt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelMainRpt.setOpaque(false);

        btnInvoice.setText("Genearate Invoces");
        btnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMainRptLayout = new javax.swing.GroupLayout(PanelMainRpt);
        PanelMainRpt.setLayout(PanelMainRptLayout);
        PanelMainRptLayout.setHorizontalGroup(
            PanelMainRptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainRptLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(btnInvoice)
                .addGap(30, 30, 30))
        );
        PanelMainRptLayout.setVerticalGroup(
            PanelMainRptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainRptLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnInvoice)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        LblMain2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        LblMain2.setText("System");

        PanelMainUserM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PanelMainUserM.setForeground(new java.awt.Color(255, 255, 255));
        PanelMainUserM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelMainUserM.setOpaque(false);

        btnGroupD.setText("Group Data");
        btnGroupD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupDActionPerformed(evt);
            }
        });

        btnCustomerD.setText("Customer Details");
        btnCustomerD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMainUserMLayout = new javax.swing.GroupLayout(PanelMainUserM);
        PanelMainUserM.setLayout(PanelMainUserMLayout);
        PanelMainUserMLayout.setHorizontalGroup(
            PanelMainUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainUserMLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(PanelMainUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGroupD, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(btnCustomerD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PanelMainUserMLayout.setVerticalGroup(
            PanelMainUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainUserMLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnCustomerD)
                .addGap(18, 18, 18)
                .addComponent(btnGroupD)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelMainTrx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelMainUserM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblMain1)
                            .addComponent(LblMain2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelMainRpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelMainUserM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PanelMainRpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(PanelMainTrx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(LblMain1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblMain2)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        PanelMainRpt.getAccessibleContext().setAccessibleName("Reports");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBillDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillDActionPerformed
        // TODO add your handling code here:
        EnterBillData enterBillData = null;
        try {
            enterBillData = new EnterBillData();
        } catch (Exception ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterBillData.setVisible(true); 
        this.setVisible(false);
        this.dispose();          
    }//GEN-LAST:event_btnBillDActionPerformed

    private void btnPaymentDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentDActionPerformed
        // TODO add your handling code here:
        EnterPayment enterPayment = null;
        try {
            enterPayment = new EnterPayment();
        } catch (Exception ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterPayment.setVisible(true); 
        this.setVisible(false);
        this.dispose();         
    }//GEN-LAST:event_btnPaymentDActionPerformed

    private void btnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceActionPerformed
        // TODO add your handling code here:
        GenerateInvoice generateInvoice = null;
        try {
            generateInvoice = new GenerateInvoice();
        } catch (Exception ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        generateInvoice.setVisible(true); 
        this.setVisible(false);
        this.dispose();               
        
    }//GEN-LAST:event_btnInvoiceActionPerformed

    private void btnUnitpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnitpriceActionPerformed
        // TODO add your handling code here:
        EnterUnitPrice enterUnitPrice = null;
        try {
            enterUnitPrice = new EnterUnitPrice();
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterUnitPrice.setVisible(true); 
        this.setVisible(false);
        this.dispose();          
    }//GEN-LAST:event_btnUnitpriceActionPerformed

    private void btnGroupDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupDActionPerformed
        // TODO add your handling code here:    
        EnterGroup enterGroup = null;
        try {
            enterGroup = new EnterGroup();
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterGroup.setVisible(true); 
        this.setVisible(false);
        this.dispose();         
    }//GEN-LAST:event_btnGroupDActionPerformed

    private void btnCustomerDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerDActionPerformed
        // TODO add your handling code here:
        EnterCustomer enterCustomer = null;
        try {
            enterCustomer = new EnterCustomer();
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        enterCustomer.setVisible(true); 
        this.setVisible(false);
        this.dispose();          
    }//GEN-LAST:event_btnCustomerDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MainPage().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblMain1;
    private javax.swing.JLabel LblMain2;
    private javax.swing.JPanel PanelMainRpt;
    private javax.swing.JPanel PanelMainTrx;
    private javax.swing.JPanel PanelMainUserM;
    private javax.swing.JButton btnBillD;
    private javax.swing.JButton btnCustomerD;
    private javax.swing.JButton btnGroupD;
    private javax.swing.JButton btnInvoice;
    private javax.swing.JButton btnPaymentD;
    private javax.swing.JButton btnUnitprice;
    // End of variables declaration//GEN-END:variables
}
