/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waterbillingsystem_1.pkg0.pkg0.view;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import waterbillingsystem_1.pkg0.pkg0.JOptionPaneCustom;
import waterbillingsystem_1.pkg0.pkg0.Validations;
import waterbillingsystem_1.pkg0.pkg0.VariableStorage;
import waterbillingsystem_1.pkg0.pkg0.controller.FillGUIComponents;
import waterbillingsystem_1.pkg0.pkg0.controller.UnitCalculatorProcessor;

/**
 *
 * @author UDISSSA1
 */
public class UnitCalculator extends javax.swing.JFrame {

    /**
     * Creates new form UnitCalculator
     * @throws java.io.IOException
     */
    public UnitCalculator() throws IOException {
        File imageFile = new File("images\\calbg.jpg");
        BufferedImage myImage = ImageIO.read(imageFile);
        this.setContentPane(new ImagePanel(myImage));
        
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);        
        ImageIcon img = new ImageIcon("images\\WaterDrop.png");
        this.setIconImage(img.getImage());  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BDCLblUnits = new javax.swing.JLabel();
        txtBDCUnitUsage = new javax.swing.JTextField();
        ckBoxSramadhana = new javax.swing.JCheckBox();
        ckBoxAbsentFee = new javax.swing.JCheckBox();
        CDFLabelMain = new javax.swing.JLabel();
        btnBDClear = new javax.swing.JButton();
        btnBDCEnter = new javax.swing.JButton();
        BDCLblBillUnits = new javax.swing.JLabel();
        BDCLblBillUnitsAns = new javax.swing.JLabel();
        BDCLblFixedCharge = new javax.swing.JLabel();
        BDCLblFixedChargeAns = new javax.swing.JLabel();
        BDCLblShramadhana = new javax.swing.JLabel();
        BDCLblShramadhanaAns = new javax.swing.JLabel();
        BDCLblPanelty = new javax.swing.JLabel();
        BDCLblPaneltyAns = new javax.swing.JLabel();
        BDCLblMonthlyTotal = new javax.swing.JLabel();
        BDCLblMonthlyTotalAns = new javax.swing.JLabel();
        btnCDHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BDCLblUnits.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblUnits.setForeground(new java.awt.Color(0, 255, 204));
        BDCLblUnits.setText("Monthly Unit Usage *");

        txtBDCUnitUsage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBDCUnitUsageKeyTyped(evt);
            }
        });

        ckBoxSramadhana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckBoxSramadhana.setForeground(new java.awt.Color(0, 255, 204));
        ckBoxSramadhana.setText("  Sramadhana Fee");

        ckBoxAbsentFee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckBoxAbsentFee.setForeground(new java.awt.Color(0, 255, 204));
        ckBoxAbsentFee.setText("  Absent Charge");

        CDFLabelMain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CDFLabelMain.setForeground(new java.awt.Color(255, 255, 0));
        CDFLabelMain.setText("Bill Data Calculater");

        btnBDClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBDClear.setText(" Clear Bill Data");
        btnBDClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDClearActionPerformed(evt);
            }
        });

        btnBDCEnter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBDCEnter.setText("Enter Bill");
        btnBDCEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDCEnterActionPerformed(evt);
            }
        });

        BDCLblBillUnits.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblBillUnits.setForeground(new java.awt.Color(0, 255, 204));
        BDCLblBillUnits.setText("Water Bill For Units");

        BDCLblBillUnitsAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblBillUnitsAns.setForeground(new java.awt.Color(0, 255, 51));
        BDCLblBillUnitsAns.setText("Rs :");

        BDCLblFixedCharge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblFixedCharge.setForeground(new java.awt.Color(0, 255, 204));
        BDCLblFixedCharge.setText("Water Bill Fixed Charge");

        BDCLblFixedChargeAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblFixedChargeAns.setForeground(new java.awt.Color(0, 255, 51));
        BDCLblFixedChargeAns.setText("Rs :");

        BDCLblShramadhana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblShramadhana.setForeground(new java.awt.Color(0, 255, 204));
        BDCLblShramadhana.setText("Shramadhana Charge");

        BDCLblShramadhanaAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblShramadhanaAns.setForeground(new java.awt.Color(0, 255, 51));
        BDCLblShramadhanaAns.setText("Rs :");

        BDCLblPanelty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblPanelty.setForeground(new java.awt.Color(0, 255, 204));
        BDCLblPanelty.setText("Penalty For Bad Attendence");

        BDCLblPaneltyAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblPaneltyAns.setForeground(new java.awt.Color(0, 255, 51));
        BDCLblPaneltyAns.setText("Rs :");

        BDCLblMonthlyTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblMonthlyTotal.setForeground(new java.awt.Color(0, 255, 204));
        BDCLblMonthlyTotal.setText("Total Monthly Amount");

        BDCLblMonthlyTotalAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDCLblMonthlyTotalAns.setForeground(new java.awt.Color(0, 255, 51));
        BDCLblMonthlyTotalAns.setText("Rs :");

        btnCDHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_button.png"))); // NOI18N
        btnCDHome.setBorder(null);
        btnCDHome.setBorderPainted(false);
        btnCDHome.setContentAreaFilled(false);
        btnCDHome.setFocusPainted(false);
        btnCDHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckBoxAbsentFee)
                            .addComponent(ckBoxSramadhana)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnBDClear)
                        .addGap(79, 79, 79)
                        .addComponent(btnBDCEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 127, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDCLblMonthlyTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(BDCLblMonthlyTotalAns, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDCLblPanelty, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BDCLblPaneltyAns, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDCLblShramadhana, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BDCLblShramadhanaAns, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDCLblFixedCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BDCLblFixedChargeAns, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDCLblBillUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BDCLblBillUnitsAns, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDCLblUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBDCUnitUsage, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(CDFLabelMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnCDHome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(CDFLabelMain))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCDHome)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDCLblUnits)
                    .addComponent(txtBDCUnitUsage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ckBoxSramadhana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckBoxAbsentFee)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBDClear)
                    .addComponent(btnBDCEnter))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDCLblBillUnits)
                    .addComponent(BDCLblBillUnitsAns))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDCLblFixedCharge)
                    .addComponent(BDCLblFixedChargeAns))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDCLblShramadhana)
                    .addComponent(BDCLblShramadhanaAns))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDCLblPanelty)
                    .addComponent(BDCLblPaneltyAns))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDCLblMonthlyTotal)
                    .addComponent(BDCLblMonthlyTotalAns))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBDCUnitUsageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBDCUnitUsageKeyTyped
        // TODO add your handling code here:
        FillGUIComponents.setNumberOnlyTextBox(evt);
    }//GEN-LAST:event_txtBDCUnitUsageKeyTyped

    private void btnBDClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDClearActionPerformed
        // TODO add your handling code here:
        txtBDCUnitUsage.setText("");
        ckBoxSramadhana.setSelected(false);
        ckBoxAbsentFee.setSelected(false);
        BDCLblBillUnitsAns.setText("Rs :");
        BDCLblFixedChargeAns.setText("Rs :");
        BDCLblShramadhanaAns.setText("Rs :");
        BDCLblPaneltyAns.setText("Rs :");
        BDCLblMonthlyTotalAns.setText("Rs :");
    }//GEN-LAST:event_btnBDClearActionPerformed

    private void btnBDCEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDCEnterActionPerformed

        if(!txtBDCUnitUsage.getText().equals(""))
            whenEnterButtonClicked();
        else
            JOptionPaneCustom.errorBox("Please enter monthly unit usage " ,"Monthly Bill Details Calculation");

        
    }//GEN-LAST:event_btnBDCEnterActionPerformed

    private void whenEnterButtonClicked(){
        UnitCalculatorProcessor unitCalculatorProcessor=new UnitCalculatorProcessor();
        try {
            double[] charges = unitCalculatorProcessor.geteConsumingBill(Integer.parseInt(txtBDCUnitUsage.getText()), ckBoxSramadhana.isSelected(), ckBoxAbsentFee.isSelected());
            BDCLblBillUnitsAns.setText(Validations.setLabelText(String.valueOf(charges[0])));
            BDCLblFixedChargeAns.setText(Validations.setLabelText(String.valueOf(VariableStorage.getFixedCharge())));
            if(ckBoxSramadhana.isSelected())
                BDCLblShramadhanaAns.setText(Validations.setLabelText(String.valueOf(VariableStorage.getSramadhanaCharge())));
            else
                BDCLblShramadhanaAns.setText("Rs. 0.0");
            if(ckBoxAbsentFee.isSelected())
                BDCLblPaneltyAns.setText(Validations.setLabelText(String.valueOf(VariableStorage.getAbsentCharge())));
            else
                BDCLblPaneltyAns.setText("Rs. 0.0");
            BDCLblMonthlyTotalAns.setText(Validations.setLabelText(String.valueOf(charges[1])));
        } catch (Exception ex) {
            Logger.getLogger(UnitCalculator.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPaneCustom.errorBox("Monthly Bill Calculate error: " +ex.getMessage(), "Monthly Bill Details Calculation");
        }    
    }
    
    
    private void btnCDHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDHomeActionPerformed
        // TODO add your handling code here:
        MainPage mainPage = null;
        try {
            mainPage = new MainPage();
        } catch (IOException ex) {
            Logger.getLogger(EnterBillData.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainPage.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCDHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new UnitCalculator().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(UnitCalculator.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BDCLblBillUnits;
    private javax.swing.JLabel BDCLblBillUnitsAns;
    private javax.swing.JLabel BDCLblFixedCharge;
    private javax.swing.JLabel BDCLblFixedChargeAns;
    private javax.swing.JLabel BDCLblMonthlyTotal;
    private javax.swing.JLabel BDCLblMonthlyTotalAns;
    private javax.swing.JLabel BDCLblPanelty;
    private javax.swing.JLabel BDCLblPaneltyAns;
    private javax.swing.JLabel BDCLblShramadhana;
    private javax.swing.JLabel BDCLblShramadhanaAns;
    private javax.swing.JLabel BDCLblUnits;
    private javax.swing.JLabel CDFLabelMain;
    private javax.swing.JButton btnBDCEnter;
    private javax.swing.JButton btnBDClear;
    private javax.swing.JButton btnCDHome;
    private javax.swing.JCheckBox ckBoxAbsentFee;
    private javax.swing.JCheckBox ckBoxSramadhana;
    private javax.swing.JTextField txtBDCUnitUsage;
    // End of variables declaration//GEN-END:variables
}
